upstream backend-service {
    least_conn;
    server tradeplay-backend:8090;
}

# Add resolver for dynamic DNS resolution
resolver 127.0.0.11 valid=30s;

server {
    listen 80;
    server_name _;
    
    resolver 127.0.0.11 valid=30s;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    
    location /backend-service/ { 
        rewrite ^/backend-service/(.*)$ /$1 break; 
        proxy_pass http://tradeplay-backend:8090;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}