import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'vi' | 'en';

interface LanguageState {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'vi',
      toggleLanguage: () =>
        set((state) => ({
          language: state.language === 'vi' ? 'en' : 'vi',
        })),
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: 'language-storage',
    }
  )
);

export const translations = {
  vi: {
    // Header
    home: '🏠 Trang Chủ',
    accounts: '🎮 Acc Game',
    guide: '📖 Hướng Dẫn',
    warranty: '🛡️ Bảo Hành',
    orders: '📦 Đơn Hàng',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    
    // Home
    shopBadge: '✨ Shop acc Play Together uy tín #1 ✨',
    heroTitle1: 'Play Together',
    heroTitle2: 'Shop 🎮💖',
    heroDescription: '🌟 Chuyên mua bán acc Play Together chất lượng cao! Nhà đẹp, outfit xịn, gems nhiều - Giá siêu hời! 🏡👗💎',
    viewAccounts: '🎮 Xem Acc Ngay',
    registerFree: '✨ Đăng ký miễn phí',
    statTransactions: '💫 Giao dịch',
    statCustomers: '💕 Khách hàng',
    statSatisfied: '😊 Hài lòng',
    statSupport: '💬 Hỗ trợ',
    whyChooseUs: 'Tại sao chọn',
    us: 'chúng mình',
    whyChooseDesc: 'Shop cam kết mang đến trải nghiệm mua acc tốt nhất cho bạn! 🌈',
    featureReliable: '🛡️ Uy tín hàng đầu',
    featureReliableDesc: 'Hơn 10,000+ giao dịch thành công, đánh giá 5 sao từ khách hàng yêu thương',
    featureHouse: '🏡 Acc có nhà đẹp',
    featureHouseDesc: 'Nhiều acc sở hữu nhà trang trí siêu cute, đầy đủ nội thất sang chảnh',
    featureOutfit: '👗 Outfit đa dạng',
    featureOutfitDesc: 'Acc với hàng trăm skin, outfit limited edition và vật phẩm hiếm',
    findByPrice: 'Tìm Acc theo',
    price: 'Giá',
    findByPriceDesc: 'Chọn khoảng giá phù hợp với túi tiền của bạn! 🎯',
    priceUnder500k: 'Dưới 500K',
    price500kTo1m: '500K - 1 Triệu',
    price1mTo2m: '1 - 2 Triệu',
    priceAbove2m: 'Trên 2 Triệu',
    priceDescCheap: 'Acc giá rẻ cho newbie',
    priceDescGood: 'Acc chất lượng tốt',
    priceDescVip: 'Acc VIP nhiều đồ',
    priceDescSuperVip: 'Acc siêu VIP rare',
    viewAllAccounts: 'Xem tất cả acc 🎮',
    readyToPlay: 'Sẵn sàng chơi Play Together? 🎮💖',
    ctaDesc: 'Mua acc ngay hôm nay để nhận ưu đãi đặc biệt! Hỗ trợ 24/7 ✨',
    buyAccNow: 'Mua Acc Ngay',
    
    // Accounts Page
    accountsList: 'Danh Sách',
    accGame: 'Acc Game',
    accountsDesc: 'Tìm kiếm và mua acc game chất lượng với giá tốt nhất',
    found: 'Tìm thấy',
    accGameCount: 'acc game',
    noAccountsFound: 'Không tìm thấy acc game',
    tryChangeFilter: 'Thử thay đổi bộ lọc hoặc từ khóa tìm kiếm',
    
    // Account Card
    details: 'Chi tiết',
    
    // Account Filter
    searchPlaceholder: 'Tìm kiếm acc game...',
    allGames: 'Tất cả',
    allPrices: 'Tất cả giá',
    clearFilters: 'Xóa bộ lọc',
    
    // Account Detail
    accountNotFound: 'Không tìm thấy acc game',
    backToList: 'Quay lại danh sách',
    back: 'Quay lại',
    inStock: 'Còn hàng',
    sold: 'Đã bán',
    description: 'Mô tả',
    highlights: 'Đặc điểm nổi bật',
    buyNow: 'Mua ngay',
    afterPaymentNote: 'Sau khi thanh toán, acc sẽ được gửi qua email của bạn',
    loginRequired: 'Yêu cầu đăng nhập',
    loginToBuy: 'Vui lòng đăng nhập để mua acc game',
    orderCreated: 'Tạo đơn hàng thành công',
    
    // Orders Page
    myOrders: 'Đơn Hàng',
    ofMe: 'Của Tôi',
    trackOrders: 'Theo dõi trạng thái các đơn hàng của bạn',
    loginToViewOrders: 'Đăng nhập để xem đơn hàng',
    loginToViewOrdersDesc: 'Bạn cần đăng nhập để xem lịch sử đơn hàng của mình',
    loginNow: 'Đăng nhập ngay',
    noOrders: 'Chưa có đơn hàng nào',
    startBuying: 'Bắt đầu mua acc game đầu tiên của bạn ngay!',
    viewAccGame: 'Xem Acc Game',
    pay: 'Thanh toán',
    statusPending: 'Chờ thanh toán',
    statusPaid: 'Đã thanh toán',
    statusDelivered: 'Đã gửi acc',
    
    // Payment Page
    orderNotFound: 'Không tìm thấy đơn hàng',
    viewMyOrders: 'Xem đơn hàng của tôi',
    waitingPayment: 'Chờ Thanh Toán',
    transferInfo: 'Vui lòng chuyển khoản theo thông tin bên dưới',
    orderId: 'Order ID',
    accGameLabel: 'Acc Game',
    totalAmount: 'Tổng tiền',
    scanQR: 'Quét mã QR MoMo',
    orTransfer: 'Hoặc chuyển khoản theo thông tin bên dưới',
    transferDetails: 'Thông tin chuyển khoản',
    momoPhone: 'Số điện thoại MoMo',
    accountName: 'Tên tài khoản',
    transferContent: 'Nội dung chuyển khoản',
    importantNote: 'Lưu ý quan trọng',
    paymentNotice: 'Sau khi chuyển khoản, vui lòng chờ admin xác nhận. Thông tin acc game sẽ được gửi qua email của bạn trong vòng 5-15 phút.',
    viewOrders: 'Xem đơn hàng',
    continueShopping: 'Tiếp tục mua sắm',
    copied: 'Đã sao chép',
    
    // Auth Page
    loginTitle: 'Đăng Nhập',
    registerTitle: 'Đăng Ký',
    loginDesc: 'Đăng nhập để mua acc game',
    registerDesc: 'Tạo tài khoản mới để bắt đầu',
    fullName: 'Họ tên',
    enterName: 'Nhập họ tên',
    email: 'Email',
    password: 'Mật khẩu',
    enterPassword: 'Nhập mật khẩu',
    processing: 'Đang xử lý...',
    noAccount: 'Chưa có tài khoản?',
    hasAccount: 'Đã có tài khoản?',
    registerNow: 'Đăng ký ngay',
    backToHome: 'Về trang chủ',
    loginSuccess: 'Đăng nhập thành công',
    welcomeBack: 'Chào mừng bạn quay trở lại!',
    loginFailed: 'Đăng nhập thất bại',
    wrongCredentials: 'Email hoặc mật khẩu không đúng',
    registerSuccess: 'Đăng ký thành công',
    accountCreated: 'Tài khoản của bạn đã được tạo!',
    registerFailed: 'Đăng ký thất bại',
    emailUsed: 'Email đã được sử dụng',
    
    // Guide Page
    guideHeader: 'Hướng dẫn chi tiết',
    guideTitle: '📖 Hướng Dẫn Mua Tài Khoản',
    guideDesc: 'Chỉ với 4 bước đơn giản, bạn có thể sở hữu acc Play Together ưng ý. Theo dõi hướng dẫn bên dưới để mua hàng dễ dàng!',
    step: 'Bước',
    step1Title: 'Tìm kiếm acc phù hợp',
    step1Desc: 'Truy cập trang Danh sách acc, sử dụng bộ lọc theo giá, game để tìm acc ưng ý.',
    step1Tips: ['Lọc theo khoảng giá phù hợp ngân sách', 'Xem kỹ hình ảnh và mô tả acc', 'Kiểm tra các thuộc tính đặc biệt'],
    step2Title: 'Xem chi tiết acc',
    step2Desc: 'Click vào acc để xem thông tin chi tiết, bao gồm hình ảnh, mô tả và các thuộc tính.',
    step2Tips: ['Xem đầy đủ hình ảnh của acc', 'Đọc kỹ mô tả về trang bị, skin', 'Kiểm tra thông tin acc có đúng nhu cầu'],
    step3Title: 'Đặt hàng & Thanh toán',
    step3Desc: 'Nhấn nút "Mua ngay" và thực hiện thanh toán theo hướng dẫn.',
    step3Tips: ['Chọn phương thức thanh toán phù hợp', 'Kiểm tra lại thông tin đơn hàng', 'Lưu lại mã đơn hàng để theo dõi'],
    step4Title: 'Nhận acc & Kiểm tra',
    step4Desc: 'Sau khi thanh toán thành công, bạn sẽ nhận được thông tin đăng nhập acc.',
    step4Tips: ['Đăng nhập và kiểm tra acc ngay', 'Đổi mật khẩu để bảo mật', 'Liên hệ hỗ trợ nếu có vấn đề'],
    tips: '💡 Mẹo hay:',
    paymentMethods: '💳 Phương Thức Thanh Toán',
    bankTransfer: 'Chuyển khoản ngân hàng',
    bankTransferDesc: 'Hỗ trợ tất cả ngân hàng nội địa',
    momo: 'Ví MoMo',
    momoDesc: 'Thanh toán nhanh qua ví điện tử',
    zalopay: 'Ví ZaloPay',
    zalopayDesc: 'Tiện lợi với ZaloPay',
    phoneCard: 'Thẻ cào điện thoại',
    phoneCardDesc: 'Viettel, Mobifone, Vinaphone',
    needSupport: 'Cần hỗ trợ?',
    supportDesc: 'Nếu bạn gặp bất kỳ vấn đề nào trong quá trình mua hàng, đừng ngần ngại liên hệ với chúng tôi qua Facebook hoặc Zalo. Đội ngũ hỗ trợ luôn sẵn sàng giúp đỡ bạn 24/7!',
    support247: '24/7',
    reliable: 'Uy tín',
    
    // Warranty Page
    warrantyHeader: 'Cam kết uy tín',
    warrantyTitle: '🛡️ Chính Sách Bảo Hành',
    warrantyDesc: 'Chúng tôi cam kết mang đến trải nghiệm mua sắm an toàn và đáng tin cậy. Mọi giao dịch đều được bảo hành theo chính sách rõ ràng.',
    warranty24h: 'Bảo hành 24h đầu tiên',
    warranty24hDesc: 'Tất cả acc được bảo hành trong 24 giờ đầu sau khi giao. Nếu có vấn đề về đăng nhập hoặc acc không đúng mô tả, chúng tôi sẽ hoàn tiền hoặc đổi acc mới.',
    freeExchange: 'Đổi acc miễn phí',
    freeExchangeDesc: 'Trong thời gian bảo hành, nếu acc gặp sự cố (bị khóa, mất items do lỗi hệ thống), bạn sẽ được đổi acc khác có giá trị tương đương.',
    fastSupport: 'Hỗ trợ nhanh chóng',
    fastSupportDesc: 'Đội ngũ hỗ trợ phản hồi trong vòng 30 phút (giờ hành chính) và tối đa 2 giờ (ngoài giờ hành chính).',
    coveredCases: 'Được bảo hành',
    notCoveredCases: 'Không bảo hành',
    covered1: 'Acc không đăng nhập được do sai thông tin',
    covered2: 'Acc bị khóa ngay sau khi nhận (do lỗi từ phía shop)',
    covered3: 'Thông tin acc không đúng với mô tả (items, skin, level...)',
    covered4: 'Acc đã được bán cho người khác trước đó',
    notCovered1: 'Acc bị khóa do người mua vi phạm chính sách game',
    notCovered2: 'Người mua chia sẻ thông tin acc cho người khác',
    notCovered3: 'Acc bị hack do người mua không bảo mật tốt',
    notCovered4: 'Yêu cầu bảo hành sau thời gian quy định (24h)',
    notCovered5: 'Người mua tự ý đổi thông tin rồi quên',
    warrantyProcess: '📋 Quy Trình Bảo Hành',
    processStep1: 'Liên hệ hỗ trợ',
    processStep1Desc: 'Gửi tin nhắn qua Facebook/Zalo kèm mã đơn hàng và mô tả vấn đề',
    processStep2: 'Xác minh thông tin',
    processStep2Desc: 'Đội ngũ sẽ kiểm tra và xác nhận vấn đề trong vòng 30 phút',
    processStep3: 'Xử lý bảo hành',
    processStep3Desc: 'Hoàn tiền hoặc đổi acc mới trong vòng 1-2 giờ sau khi xác nhận',
    importantNotice: '⚠️ Lưu ý quan trọng',
    notice1: 'Sau khi nhận acc, vui lòng <strong>đổi mật khẩu ngay</strong> để bảo mật.',
    notice2: '<strong>Không chia sẻ</strong> thông tin đăng nhập cho bất kỳ ai.',
    notice3: 'Lưu lại <strong>mã đơn hàng</strong> để tiện theo dõi và bảo hành.',
    notice4: 'Kiểm tra acc <strong>ngay sau khi nhận</strong> để đảm bảo quyền lợi bảo hành.',
    requestWarranty: 'Yêu cầu bảo hành',
    requestWarrantyDesc: 'Liên hệ ngay với chúng tôi qua Facebook hoặc Zalo kèm mã đơn hàng để được hỗ trợ nhanh nhất. Đội ngũ luôn sẵn sàng giải quyết mọi vấn đề của bạn!',
    
    // Footer
    footerDesc: '✨ Shop bán acc Play Together uy tín hàng đầu Việt Nam. Giao dịch an toàn, hỗ trợ 24/7! 🎮',
    quickLinks: '🔗 Liên kết',
    homeLink: '🏠 Trang chủ',
    accountsLink: '🎮 Danh sách acc',
    guideLink: '📖 Hướng dẫn mua',
    warrantyLink: '🛡️ Chính sách bảo hành',
    ordersLink: '📦 Đơn hàng',
    hotCategories: '🌟 Loại acc hot',
    categoryHouse: '🏡 Acc có nhà đẹp',
    categorySkin: '👗 Acc nhiều skin',
    categoryOutfit: '🎭 Acc VIP outfit',
    categoryGems: '💎 Acc giàu gems',
    contactLabel: '📞 Liên hệ',
    madeWith: 'Made with',
    by: 'by PlayTogether Shop',
  },
  en: {
    // Header
    home: '🏠 Home',
    accounts: '🎮 Accounts',
    guide: '📖 Guide',
    warranty: '🛡️ Warranty',
    orders: '📦 Orders',
    login: 'Login',
    logout: 'Logout',
    
    // Home
    shopBadge: '✨ #1 Trusted Play Together Account Shop ✨',
    heroTitle1: 'Play Together',
    heroTitle2: 'Shop 🎮💖',
    heroDescription: '🌟 Premium Play Together accounts! Beautiful houses, cool outfits, lots of gems - Best prices! 🏡👗💎',
    viewAccounts: '🎮 View Accounts',
    registerFree: '✨ Register Free',
    statTransactions: '💫 Transactions',
    statCustomers: '💕 Customers',
    statSatisfied: '😊 Satisfied',
    statSupport: '💬 Support',
    whyChooseUs: 'Why choose',
    us: 'us',
    whyChooseDesc: 'We commit to bringing you the best account buying experience! 🌈',
    featureReliable: '🛡️ Top Trusted',
    featureReliableDesc: 'Over 10,000+ successful transactions, 5-star reviews from beloved customers',
    featureHouse: '🏡 Beautiful Houses',
    featureHouseDesc: 'Many accounts with super cute decorated houses, full luxury furniture',
    featureOutfit: '👗 Diverse Outfits',
    featureOutfitDesc: 'Accounts with hundreds of skins, limited edition outfits and rare items',
    findByPrice: 'Find Accounts by',
    price: 'Price',
    findByPriceDesc: 'Choose a price range that fits your budget! 🎯',
    priceUnder500k: 'Under 500K',
    price500kTo1m: '500K - 1 Million',
    price1mTo2m: '1 - 2 Million',
    priceAbove2m: 'Above 2 Million',
    priceDescCheap: 'Budget accounts for newbies',
    priceDescGood: 'Good quality accounts',
    priceDescVip: 'VIP accounts with many items',
    priceDescSuperVip: 'Super VIP rare accounts',
    viewAllAccounts: 'View all accounts 🎮',
    readyToPlay: 'Ready to play Play Together? 🎮💖',
    ctaDesc: 'Buy an account today for special offers! 24/7 support ✨',
    buyAccNow: 'Buy Account Now',
    
    // Accounts Page
    accountsList: 'Account',
    accGame: 'List',
    accountsDesc: 'Search and buy quality game accounts at the best prices',
    found: 'Found',
    accGameCount: 'accounts',
    noAccountsFound: 'No accounts found',
    tryChangeFilter: 'Try changing filters or search keywords',
    
    // Account Card
    details: 'Details',
    
    // Account Filter
    searchPlaceholder: 'Search game accounts...',
    allGames: 'All Games',
    allPrices: 'All Prices',
    clearFilters: 'Clear Filters',
    
    // Account Detail
    accountNotFound: 'Account not found',
    backToList: 'Back to list',
    back: 'Back',
    inStock: 'In Stock',
    sold: 'Sold',
    description: 'Description',
    highlights: 'Key Features',
    buyNow: 'Buy Now',
    afterPaymentNote: 'After payment, the account will be sent to your email',
    loginRequired: 'Login Required',
    loginToBuy: 'Please login to buy game accounts',
    orderCreated: 'Order created successfully',
    
    // Orders Page
    myOrders: 'My',
    ofMe: 'Orders',
    trackOrders: 'Track the status of your orders',
    loginToViewOrders: 'Login to view orders',
    loginToViewOrdersDesc: 'You need to login to view your order history',
    loginNow: 'Login Now',
    noOrders: 'No orders yet',
    startBuying: 'Start buying your first game account now!',
    viewAccGame: 'View Accounts',
    pay: 'Pay',
    statusPending: 'Pending Payment',
    statusPaid: 'Paid',
    statusDelivered: 'Delivered',
    
    // Payment Page
    orderNotFound: 'Order not found',
    viewMyOrders: 'View my orders',
    waitingPayment: 'Waiting for Payment',
    transferInfo: 'Please transfer according to the information below',
    orderId: 'Order ID',
    accGameLabel: 'Game Account',
    totalAmount: 'Total Amount',
    scanQR: 'Scan MoMo QR Code',
    orTransfer: 'Or transfer according to the information below',
    transferDetails: 'Transfer Information',
    momoPhone: 'MoMo Phone Number',
    accountName: 'Account Name',
    transferContent: 'Transfer Content',
    importantNote: 'Important Note',
    paymentNotice: 'After transferring, please wait for admin confirmation. Account info will be sent to your email within 5-15 minutes.',
    viewOrders: 'View Orders',
    continueShopping: 'Continue Shopping',
    copied: 'Copied',
    
    // Auth Page
    loginTitle: 'Login',
    registerTitle: 'Register',
    loginDesc: 'Login to buy game accounts',
    registerDesc: 'Create a new account to get started',
    fullName: 'Full Name',
    enterName: 'Enter your name',
    email: 'Email',
    password: 'Password',
    enterPassword: 'Enter password',
    processing: 'Processing...',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    registerNow: 'Register now',
    backToHome: 'Back to home',
    loginSuccess: 'Login successful',
    welcomeBack: 'Welcome back!',
    loginFailed: 'Login failed',
    wrongCredentials: 'Wrong email or password',
    registerSuccess: 'Registration successful',
    accountCreated: 'Your account has been created!',
    registerFailed: 'Registration failed',
    emailUsed: 'Email already in use',
    
    // Guide Page
    guideHeader: 'Detailed Guide',
    guideTitle: '📖 Account Buying Guide',
    guideDesc: 'In just 4 simple steps, you can own your desired Play Together account. Follow the guide below to shop easily!',
    step: 'Step',
    step1Title: 'Find the right account',
    step1Desc: 'Visit the Accounts page, use filters by price and game to find your perfect account.',
    step1Tips: ['Filter by budget-friendly price range', 'Check images and account description carefully', 'Review special attributes'],
    step2Title: 'View account details',
    step2Desc: 'Click on an account to view detailed information, including images, description and attributes.',
    step2Tips: ['View all account images', 'Read equipment and skin descriptions carefully', 'Check if account info matches your needs'],
    step3Title: 'Order & Payment',
    step3Desc: 'Click "Buy Now" button and complete payment following the instructions.',
    step3Tips: ['Choose a suitable payment method', 'Double-check order information', 'Save order ID for tracking'],
    step4Title: 'Receive & Check',
    step4Desc: 'After successful payment, you will receive the account login information.',
    step4Tips: ['Login and check the account immediately', 'Change password for security', 'Contact support if there are issues'],
    tips: '💡 Pro tips:',
    paymentMethods: '💳 Payment Methods',
    bankTransfer: 'Bank Transfer',
    bankTransferDesc: 'All domestic banks supported',
    momo: 'MoMo Wallet',
    momoDesc: 'Fast payment via e-wallet',
    zalopay: 'ZaloPay Wallet',
    zalopayDesc: 'Convenient with ZaloPay',
    phoneCard: 'Phone Card',
    phoneCardDesc: 'Viettel, Mobifone, Vinaphone',
    needSupport: 'Need help?',
    supportDesc: 'If you encounter any issues during the purchase process, feel free to contact us via Facebook or Zalo. Our support team is always ready to help you 24/7!',
    support247: '24/7',
    reliable: 'Trusted',
    
    // Warranty Page
    warrantyHeader: 'Trusted Commitment',
    warrantyTitle: '🛡️ Warranty Policy',
    warrantyDesc: 'We are committed to providing a safe and reliable shopping experience. All transactions are covered by a clear warranty policy.',
    warranty24h: '24-hour Warranty',
    warranty24hDesc: 'All accounts are warranted for the first 24 hours after delivery. If there are login issues or the account does not match the description, we will refund or exchange for a new account.',
    freeExchange: 'Free Exchange',
    freeExchangeDesc: 'During the warranty period, if the account has issues (locked, lost items due to system error), you will get an exchange for an equivalent account.',
    fastSupport: 'Fast Support',
    fastSupportDesc: 'Support team responds within 30 minutes (business hours) and maximum 2 hours (after hours).',
    coveredCases: 'Covered',
    notCoveredCases: 'Not Covered',
    covered1: 'Account cannot login due to wrong information',
    covered2: 'Account locked right after receiving (shop error)',
    covered3: 'Account info does not match description (items, skin, level...)',
    covered4: 'Account was sold to someone else before',
    notCovered1: 'Account locked due to buyer violating game policy',
    notCovered2: 'Buyer shared account info with others',
    notCovered3: 'Account hacked due to buyer not securing properly',
    notCovered4: 'Warranty request after the specified time (24h)',
    notCovered5: 'Buyer changed info themselves and forgot',
    warrantyProcess: '📋 Warranty Process',
    processStep1: 'Contact Support',
    processStep1Desc: 'Send a message via Facebook/Zalo with order ID and issue description',
    processStep2: 'Verify Information',
    processStep2Desc: 'Team will check and confirm the issue within 30 minutes',
    processStep3: 'Process Warranty',
    processStep3Desc: 'Refund or exchange new account within 1-2 hours after confirmation',
    importantNotice: '⚠️ Important Notice',
    notice1: 'After receiving the account, please <strong>change password immediately</strong> for security.',
    notice2: '<strong>Do not share</strong> login information with anyone.',
    notice3: 'Save your <strong>order ID</strong> for tracking and warranty.',
    notice4: 'Check the account <strong>immediately after receiving</strong> to ensure warranty rights.',
    requestWarranty: 'Request Warranty',
    requestWarrantyDesc: 'Contact us immediately via Facebook or Zalo with your order ID for the fastest support. Our team is always ready to solve any of your problems!',
    
    // Footer
    footerDesc: '✨ #1 Trusted Play Together account shop in Vietnam. Safe transactions, 24/7 support! 🎮',
    quickLinks: '🔗 Links',
    homeLink: '🏠 Home',
    accountsLink: '🎮 Account List',
    guideLink: '📖 Buying Guide',
    warrantyLink: '🛡️ Warranty Policy',
    ordersLink: '📦 Orders',
    hotCategories: '🌟 Hot Categories',
    categoryHouse: '🏡 Beautiful House Acc',
    categorySkin: '👗 Many Skins Acc',
    categoryOutfit: '🎭 VIP Outfit Acc',
    categoryGems: '💎 Rich Gems Acc',
    contactLabel: '📞 Contact',
    madeWith: 'Made with',
    by: 'by PlayTogether Shop',
  },
};

export const useTranslation = () => {
  const { language } = useLanguageStore();
  
  const t = (key: keyof typeof translations.vi, params?: Record<string, string | number>): string => {
    const value = translations[language][key];
    if (Array.isArray(value)) {
      return value as unknown as string;
    }
    let text = (value || key) as string;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  const tArray = (key: keyof typeof translations.vi): string[] => {
    const value = translations[language][key];
    return Array.isArray(value) ? value : [value as string];
  };
  
  return { t, tArray, language };
};
